(defun color-theme-blue-gnus ()
  "Color theme for gnus and message faces only.
This is intended for other color themes to use (eg. `color-theme-gnome2'
and `color-theme-blue-sea')."
  (interactive)
  (color-theme-install
   '(color-theme-blue-gnus
     nil
     (gnus-cite-attribution-face ((t (:lforeground "#fffacd" :bold t))))
     (gnus-cite-face-1 ((t (:foreground "#ffa07a"))))
     (gnus-cite-face-2 ((t (:foreground "#f0e68c"))))
     (gnus-cite-face-3 ((t (:foreground "#ff7f50"))))
     (gnus-cite-face-4 ((t (:foreground "#9acd32"))))
     (gnus-cite-face-5 ((t (:foreground "#bdb76b"))))
     (gnus-cite-face-6 ((t (:foreground "#ffe4c4"))))
     (gnus-cite-face-7 ((t (:foreground "#cd853f"))))
     (gnus-cite-face-8 ((t (:foreground "#f08080"))))
     (gnus-cite-face-9 ((t (:foreground "#dda0dd"))))
     (gnus-emphasis-bold ((t (:bold t))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t))))
     (gnus-emphasis-highlight-words ((t (:background "#000000" :foreground "#ffff00"))))
     (gnus-emphasis-italic ((t (:italic t))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t))))
     (gnus-group-mail-1-empty-face ((t (:foreground "#ffffff"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "#ffffff"))))
     (gnus-group-mail-2-empty-face ((t (:foreground "#e0ffff"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "#e0ffff"))))
     (gnus-group-mail-3-empty-face ((t (:foreground "#add8e6"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "#add8e6"))))
     (gnus-group-mail-low-empty-face ((t (:foreground "#7fffd4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "#7fffd4"))))
     (gnus-group-news-1-empty-face ((t (:foreground "#ffffff"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "#ffffff"))))
     (gnus-group-news-2-empty-face ((t (:foreground "#e0ffff"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "#e0ffff"))))
     (gnus-group-news-3-empty-face ((t (:foreground "#add8e6"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "#add8e6"))))
     (gnus-group-news-4-empty-face ((t (:foreground "#7fffd4"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "#7fffd4"))))
     (gnus-group-news-5-empty-face ((t (:foreground "#66cdaa"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "#66cdaa"))))
     (gnus-group-news-6-empty-face ((t (:foreground "#66cdaa"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "#66cdaa"))))
     (gnus-group-news-low-empty-face ((t (:foreground "#66cdaa"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "#66cdaa"))))
     (gnus-header-content-face ((t (:foreground "#8db6cd"))))
     (gnus-header-from-face ((t (:bold t :foreground "#e0ffff"))))
     (gnus-header-name-face ((t (:bold t :foreground "#add8e6"))))
     (gnus-header-newsgroups-face ((t (:bold t :foreground "#66cdaa"))))
     (gnus-header-subject-face ((t (:bold t :foreground "#e0ffff"))))
     (gnus-signature-face ((t (:foreground "#bebebe"))))
     (gnus-splash-face ((t (:foreground "#228b22"))))
     (gnus-summary-cancelled-face ((t (:background "#000000" :foreground "#ffff00"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "#66cdaa"))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "#7fffd4"))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "#ffa07a"))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "#f5f5dc"))))
     (gnus-summary-low-ancient-face ((t (:foreground "#696969"))))
     (gnus-summary-low-read-face ((t (:foreground "#708090"))))
     (gnus-summary-low-ticked-face ((t (:foreground "#ffc0cb"))))
     (gnus-summary-low-unread-face ((t (:foreground "#d3d3d3"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "#66cdaa"))))
     (gnus-summary-normal-read-face ((t (:foreground "#7fffd4"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "#ffa07a"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:background "#483d8b"))))
     (message-cited-text-face ((t (:foreground "#ffa07a"))))
     (message-header-cc-face ((t (:foreground "#e0ffff"))))
     (message-header-name-face ((t (:foreground "#add8e6"))))
     (message-header-newsgroups-face ((t (:bold t :foreground "#66cdaa"))))
     (message-header-other-face ((t (:foreground "#66cdaa"))))
     (message-header-subject-face ((t (:bold t :foreground "#e0ffff"))))
     (message-header-to-face ((t (:bold t :foreground "#e0ffff"))))
     (message-header-xheader-face ((t (:foreground "#66cdaa"))))
     (message-separator-face ((t (:foreground "#d2691e")))))))


(defun color-theme-blue-erc ()
  "Color theme for erc faces only.
This is intended for other color themes to use (eg. `color-theme-gnome2')."
  (color-theme-install
   '(color-theme-blue-erc
     nil
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (:bold t))))
     (erc-current-nick-face ((t (:bold t :foreground "#ffff00"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "#98fb98"))))
     (erc-error-face ((t (:bold t :foreground "#cd5c5c"))))
     (erc-highlight-face ((t (:bold t :foreground "#98fb98"))))
     (erc-input-face ((t (:foreground "#add8e6"))))
     (erc-inverse-face ((t (:background "#4682b4"))))
     (erc-keyword-face ((t (:foreground "#ffa500" :bold t))))
     (erc-notice-face ((t  (:foreground "#ffa07a"))))
     (erc-notice-face ((t (:foreground "#66cdaa"))))
     (erc-pal-face ((t (:foreground "#98fb98"))))
     (erc-prompt-face  ((t  (:foreground "#add8e6" :bold t))))
     (fg:erc-color-face0 ((t (:foreground "#ffffff"))))
     (fg:erc-color-face1 ((t (:foreground "#f5f5dc"))))
     (fg:erc-color-face2 ((t (:foreground "#fffacd"))))
     (fg:erc-color-face3 ((t (:foreground "#e0ffff"))))
     (fg:erc-color-face4 ((t (:foreground "#b0e0e6"))))
     (fg:erc-color-face5 ((t (:foreground "#87ceeb"))))
     (fg:erc-color-face6 ((t (:foreground "#8fbc8f"))))
     (fg:erc-color-face7 ((t (:foreground "#98fb98"))))
     (fg:erc-color-face8 ((t (:foreground "#00fa9a"))))
     (fg:erc-color-face9 ((t (:foreground "#f0e68c"))))
     (fg:erc-color-face10 ((t (:foreground "#eee8aa"))))
     (fg:erc-color-face11 ((t (:foreground "#fafad2"))))
     (fg:erc-color-face12 ((t (:foreground "#ffffe0"))))
     (fg:erc-color-face13 ((t (:foreground "#ffff00"))))
     (fg:erc-color-face14 ((t (:foreground "#eedd82"))))
     (fg:erc-color-face15 ((t (:foreground "#32cd32"))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil)))))))

(defun color-theme-blue-eshell ()
  "Color theme for eshell faces only.
This is intended for other color themes to use (eg. `color-theme-gnome2')."
  (interactive)
  (color-theme-install
   '(color-theme-blue-eshell
     nil
     (eshell-ls-archive-face ((t (:bold t :foreground "#cd5c5c"))))
     (eshell-ls-backup-face ((t (:foreground "#bebebe"))))
     (eshell-ls-clutter-face ((t (:foreground "#696969"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "#7b68ee"))))
     (eshell-ls-executable-face ((t (:foreground "#ff7f50"))))
     (eshell-ls-missing-face ((t (:foreground "#000000"))))
     (eshell-ls-picture-face ((t (:foreground "#ee82ee")))) ; non-standard face
     (eshell-ls-product-face ((t (:foreground "#ffa07a"))))
     (eshell-ls-readonly-face ((t (:foreground "#7fffd4"))))
     (eshell-ls-special-face ((t (:foreground "#ffd700"))))
     (eshell-ls-symlink-face ((t (:foreground "#ffffff"))))
     (eshell-ls-text-face ((t (:foreground "#66cdaa")))) ; non-standard face
     (eshell-ls-todo-face ((t (:bold t :foreground "#7fffd4")))) ; non-standard face
     (eshell-ls-unreadable-face ((t (:foreground "#696969"))))
     (eshell-prompt-face ((t (:foreground "#b0e0e6")))))))


(defun color-theme-salmon-font-lock ()
  "Color theme for font-lock faces only.
This is intended for other color themes to use (eg. `color-theme-gnome2')."
  (interactive)
  (color-theme-install
   '(color-theme-salmon-font-lock
     nil
     (font-lock-builtin-face ((t (:bold t :foreground "#98fb98"))))
     (font-lock-comment-face ((t (:foreground "#add8e6"))))
     (font-lock-constant-face ((t (:foreground "#7fffd4"))))
     (font-lock-doc-string-face ((t (:foreground "#ffa07a"))))
     (font-lock-function-name-face ((t (:bold t :foreground "#7fffd4"))))
     (font-lock-keyword-face ((t (:foreground "#fa8072"))))
     (font-lock-preprocessor-face ((t (:foreground "#fa8072"))))
     (font-lock-reference-face ((t (:foreground "#98fb98"))))
     (font-lock-string-face ((t (:foreground "#ffa07a"))))
     (font-lock-type-face ((t (:bold t :foreground "#9acd32"))))
     (font-lock-variable-name-face ((t (:bold t :foreground "#7fffd4"))))
     (font-lock-warning-face ((t (:bold t :foreground "#ff0000")))))))

(defun color-theme-salmon-diff ()
  "Salmon and aquamarine faces for diff and change-log modes.
This is intended for other color themes to use (eg. `color-theme-gnome2')."
  (color-theme-install
   '(color-theme-salmon-diff
     nil
     (change-log-acknowledgement-face ((t (:foreground "#add8e6"))))
     (change-log-conditionals-face ((t (:bold t :weight bold :foreground "#7fffd4"))))
     (change-log-date-face ((t (:foreground "#ffa07a"))))
     (change-log-email-face ((t (:bold t :weight bold :foreground "#7fffd4"))))
     (change-log-file-face ((t (:bold t :weight bold :foreground "#7fffd4"))))
     (change-log-function-face ((t (:bold t :weight bold :foreground "#7fffd4"))))
     (change-log-list-face ((t (:foreground "#fa8072"))))
     (change-log-name-face ((t (:foreground "#7fffd4"))))
     (diff-added-face ((t (nil))))
     (diff-changed-face ((t (nil))))
     (diff-context-face ((t (:foreground "#b3b3b3"))))
     (diff-file-header-face ((t (:bold t))))
     (diff-function-face ((t (:foreground "#b3b3b3"))))
     (diff-header-face ((t (:foreground "#ffa07a"))))
     (diff-hunk-header-face ((t (:foreground "#ffa07a"))))
     (diff-index-face ((t (:bold t))))
     (diff-nonexistent-face ((t (:bold t))))
     (diff-removed-face ((t (nil))))
     (log-view-message-face ((t (:foreground "#ffa07a")))))))


(defun color-theme-gnome2 ()
  "Wheat on darkslategrey scheme.
`color-theme-gnome' started it all.

This theme supports standard faces, font-lock, eshell, info, message,
gnus, custom, widget, woman, diary, cperl, bbdb, and erc.  This theme
includes faces for Emacs and XEmacs.

The theme does not support w3 faces because w3 faces can be controlled
by your default style sheet.

This is what you should put in your .Xdefaults file, if you want to
change the colors of the menus in Emacs 20 as well:

emacs*Background:		DarkSlateGray
emacs*Foreground:		Wheat"
  (interactive)
  (color-theme-blue-gnus)
  (let ((color-theme-is-cumulative t))
    (color-theme-blue-erc)
    (color-theme-blue-eshell)
    (color-theme-salmon-font-lock)
    (color-theme-salmon-diff)
    (color-theme-install
     '(color-theme-gnome2
       ((foreground-color . "#f5deb3")
	(background-color . "#2f4f4f")
	(mouse-color . "#bebebe")
	(cursor-color . "#d3d3d3")
	(border-color . "#000000")
	(background-mode . dark))
       ((apropos-keybinding-face . underline)
	(apropos-label-face . italic)
	(apropos-match-face . secondary-selection)
	(apropos-property-face . bold-italic)
	(apropos-symbol-face . info-xref)
	(goto-address-mail-face . message-header-to-face)
	(goto-address-mail-mouse-face . secondary-selection)
	(goto-address-url-face . info-xref)
	(goto-address-url-mouse-face . highlight)
	(list-matching-lines-face . bold)
	(view-highlight-face . highlight))
       (default ((t (nil))))
       (bbdb-company ((t (:foreground "#98fb98"))))
       (bbdb-name ((t (:bold t :foreground "#98fb98"))))
       (bbdb-field-name ((t (:foreground "#3cb371"))))
       (bbdb-field-value ((t (:foreground "#8fbc8f"))))
       (bold ((t (:bold t))))
       (bold-italic ((t (:italic t :bold t :foreground "#f5f5dc"))))
       (calendar-today-face ((t (:underline t))))
       (comint-highlight-prompt ((t (:foreground "#66cdaa"))))
       (cperl-array-face ((t (:foreground "#ffff00"))))
       (cperl-hash-face ((t (:foreground "#ffffff"))))
       (cperl-nonoverridable-face ((t (:foreground "#87ceeb"))))
       (custom-button-face ((t (:underline t :foreground "#7b68ee"))))
       (custom-documentation-face ((t (:foreground "#bebebe"))))
       (custom-group-tag-face ((t (:foreground "#66cdaa"))))
       (custom-state-face ((t (:foreground "#ffa07a"))))
       (custom-variable-tag-face ((t (:foreground "#7fffd4"))))
       (diary-face ((t (:foreground "#cd5c5c"))))
       (dired-face-directory ((t (:bold t :foreground "#87ceeb"))))
       (dired-face-permissions ((t (:foreground "#7fffd4"))))
       (dired-face-flagged ((t (:foreground "#ff6347"))))
       (dired-face-marked ((t (:foreground "#ffa07a"))))
       (dired-face-executable ((t (:foreground "#adff2f"))))
       (fringe ((t (:background "#2f4f4f"))))
       (highlight ((t (:background "#98fb98" :foreground "#006400"))))
       (highline-face ((t (:background "#2e8b57"))))
       (holiday-face ((t (:background "#696969"))))
       (hyper-apropos-hyperlink ((t (:bold t :foreground "#1e90ff"))))
       (hyper-apropos-documentation ((t (:foreground "#ffa07a"))))
       (info-header-xref ((t (:foreground "#1e90ff" :bold t))))
       (info-menu-5 ((t (:underline t))))
       (info-node ((t (:underline t :bold t :foreground "#1e90ff"))))
       (info-xref ((t (:bold t :foreground "#1e90ff"))))
       (isearch ((t (:background "#2e8b57"))))
       (italic ((t (:italic t))))
       (menu ((t (:foreground "#f5deb3" :background "#2f4f4f"))))
       (modeline ((t (:background "#556b2f" :foreground "#f5deb3"))))
       (modeline-buffer-id ((t (:background "#556b2f" :foreground "#f5f5dc"))))
       (modeline-mousable ((t (:background "#556b2f" :foreground "#9acd32"))))
       (modeline-mousable-minor-mode ((t (:background "#556b2f" :foreground "#f5deb3"))))
       (region ((t (:background "#008b8b" :foreground "#00ffff"))))
       (secondary-selection ((t (:background "#7fffd4" :foreground "#6a5acd"))))
       (show-paren-match-face ((t (:bold t :background "#7fffd4" :foreground "#4682b4"))))
       (show-paren-mismatch-face ((t (:background "#ff0000" :foreground "#ffffff"))))
       (underline ((t (:underline t))))
       (widget-field-face ((t (:foreground "#add8e6"))))
       (widget-inactive-face ((t (:foreground "#696969"))))
       (widget-single-line-field-face ((t (:foreground "#add8e6"))))
       (w3m-anchor-face ((t (:bold t :foreground "#1e90ff"))))
       (w3m-arrived-anchor-face ((t (:bold t :foreground "#27408b"))))
       (w3m-header-line-location-title-face ((t (:foreground "#f5f5dc" :background "#556b2f"))))
       (w3m-header-line-location-content-face ((t (:foreground "#f5deb3" :background "#556b2f"))))
       (woman-bold-face ((t (:bold t))))
       (woman-italic-face ((t (:foreground "#f5f5dc"))))
       (woman-unknown-face ((t (:foreground "#ffa07a"))))
       (zmacs-region ((t (:background "#008b8b" :foreground "#00ffff"))))))))
